name: e_market
description: "Flutter marketplace"

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

#--------- PACKAGES -------#
dependencies:
  flutter:
    sdk: flutter
  #Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.6

  #state mangement
  get: ^4.6.5

  #product specifiic


#---------END PACKAGES -------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

#local assets
  assets:
    - assets/logos/
    - assets/icons/
    - assets/images/

#local fonts
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800